name: ブランチ保護ルールの設定

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/branch-protection.yml'
  
  workflow_dispatch:

jobs:
  set-branch-protection:
    runs-on: ubuntu-latest
    steps:
      - name: ブランチ保護ルールの設定
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl --request PUT \
          --url https://api.github.com/repos/${{ github.repository }}/branches/main/protection \
          --header "authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          --header "content-type: application/json" \
          --data '{
            "required_status_checks": {
              "strict": true,
              "contexts": []
            },
            "enforce_admins": false,
            "required_pull_request_reviews": {
              "dismissal_restrictions": {},
              "dismiss_stale_reviews": true,
              "require_code_owner_reviews": true,
              "required_approving_review_count": 1
            },
            "restrictions": null
          }' 